# Generated by Django 5.1.6 on 2025-02-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1-KURS'), (2, '2-KURS'), (3, '3-KURS'), (4, '4-KURS')], null=True, verbose_name='KURS'),
        ),
    ]
