# Generated by Django 5.1.6 on 2025-02-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='avatar'),
        ),
    ]
